directories:
  output: release
  buildResources: build
appId: com.synfeed.app
productName: SynFeed
files:
  - filter:
      - dist/**
      - electron/**
      - package.json
extraMetadata:
  main: electron/main.cjs
asar: true
win:
  target:
    - nsis
  artifactName: SynFeed-${version}-win-${arch}.${ext}
  icon: build/icon.ico
nsis:
  oneClick: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: SynFeed
electronVersion: 31.7.7
