name: Build & Release Installers

on:
  push:
    tags:
      - 'v*'           # only run when you push a tag like v1.0.6
  workflow_dispatch:    # allow manual runs

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        # electron-builder needs this
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci || npm install
      - name: Build Windows installer
        run: npm run build:win
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SynFeed-windows
          path: |
            release/**/*.exe
            release/**/*.msi
            release/**/*.zip
            release/latest.yml
          if-no-files-found: error
      - name: Attach to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*.exe
            release/latest.yml
